# Generated by Django 4.1.13 on 2023-12-01 16:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contact", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="contact",
            unique_together={("user", "phone_number")},
        ),
    ]
