# Generated by Django 4.2.4 on 2023-11-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chats", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filemessage",
            name="text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
