# Generated by Django 4.1.13 on 2023-12-10 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("chats", "0002_remove_message_file_storyreplymessage_file_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AudioMessage",
            fields=[
                (
                    "filemessage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="chats.filemessage",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("chats.filemessage",),
        ),
        migrations.CreateModel(
            name="ImageMessage",
            fields=[
                (
                    "filemessage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="chats.filemessage",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("chats.filemessage",),
        ),
        migrations.CreateModel(
            name="PositionMessage",
            fields=[
                (
                    "messagetype_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="chats.messagetype",
                    ),
                ),
                ("lat", models.FloatField()),
                ("lng", models.FloatField()),
                ("label", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("chats.messagetype",),
        ),
        migrations.CreateModel(
            name="VideoMessage",
            fields=[
                (
                    "filemessage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="chats.filemessage",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("chats.filemessage",),
        ),
    ]
