# Generated by Django 4.2.4 on 2023-11-03 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("story", "0001_initial"),
        ("chats", "0002_alter_filemessage_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="LinkMessage",
            fields=[
                (
                    "messagetype_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="chats.messagetype",
                    ),
                ),
                ("url", models.URLField()),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("chats.messagetype",),
        ),
        migrations.CreateModel(
            name="StoryReplyMessage",
            fields=[
                (
                    "messagetype_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="chats.messagetype",
                    ),
                ),
                (
                    "story",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="story.story"
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("chats.messagetype",),
        ),
        migrations.RemoveField(
            model_name="storyviewer",
            name="story",
        ),
        migrations.RemoveField(
            model_name="storyviewer",
            name="user",
        ),
        migrations.DeleteModel(
            name="Story",
        ),
        migrations.DeleteModel(
            name="StoryViewer",
        ),
    ]
