# Generated by Django 4.1.13 on 2023-11-06 19:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chats", "0002_alter_conversationuser_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="users",
            field=models.ManyToManyField(
                related_name="participants",
                through="chats.ConversationUser",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
