# Generated by Django 4.1.13 on 2023-12-10 14:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chats", "0003_audiomessage_imagemessage_positionmessage_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="imagemessage",
            name="filemessage_ptr",
        ),
        migrations.RemoveField(
            model_name="videomessage",
            name="filemessage_ptr",
        ),
        migrations.DeleteModel(
            name="AudioMessage",
        ),
        migrations.DeleteModel(
            name="ImageMessage",
        ),
        migrations.DeleteModel(
            name="VideoMessage",
        ),
    ]
