# Generated by Django 4.2.4 on 2023-11-03 12:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PostComments",
            new_name="PostComment",
        ),
    ]
