# Generated by Django 4.2.4 on 2023-09-04 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("channel", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="poll",
        ),
        migrations.AddField(
            model_name="poll",
            name="post",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="poll",
                to="channel.post",
            ),
        ),
    ]
