# Generated by Django 4.2.4 on 2023-09-04 21:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("channel", "0002_remove_post_poll_poll_post"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
    ]
